notifications:
  email: false
language: python
python:
  - "2.7"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH TMPDIR=$TRAVIS_BUILD_DIR/tmp
addons:
  firefox: "38.0"
  postgresql: 9.3
before_install:
  - mkdir tmp
  - travis_retry sudo apt-get update -y -qq
  - sh -e /etc/init.d/xvfb start
  # Install python-sopnet
  - git clone https://github.com/catsop/python-sopnet.git
  - cd python-sopnet
  - git submodule update --init
  - travis_retry sudo add-apt-repository --yes ppa:purplekarrot/cmake # precise PPA for cmake > 3
  - travis_retry sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test # precise PPA for GCC >= 4.8
  - travis_retry sudo add-apt-repository --yes ppa:boost-latest/ppa # precise PPA for Boost >= 1.49
  - travis_retry sudo apt-get update -y -qq
  - travis_retry sudo apt-get install cmake cmake-data
  - travis_retry sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  # GCC crashes with more than one job because of travis memory limits.
  - sed -i 's/make -j`[^`]*`/make -j1/g' compile_wrapper.sh
  - travis_retry sudo apt-get install -y -qq $(< packagelist-ubuntu-12.04-apt.txt)
  - python setup.py install
  - cd ..
install:
  - travis_retry sudo apt-get install -y -qq $(< packagelist-ubuntu-12.04-apt.txt)
  - travis_retry pip install -q pip==1.5.4
  - travis_retry travis_wait pip install -q numpy==1.6.1 distribute==0.7.3
  - travis_retry travis_wait 60 pip install -q -r django/pip-frozen
  # Install additional dependencies for Travis
  - pip install coveralls
  - npm install jshint qunit-phantomjs-runner
before_script:
  - psql -c 'CREATE DATABASE catmaid;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres catmaid
  - cd django
  - cp configuration.py.example configuration.py
  - sed -i -e "s?^\(abs_catmaid_path = \).*?\1'$(pwd)'?g" configuration.py
  - sed -i -e "s?^\(abs_virtualenv_python_library_path = \).*?\1'$(echo $VIRTUAL_ENV)'?g" configuration.py
  - sed -i -e "s?^\(catmaid_database_name = \).*?\1'catmaid'?g" configuration.py
  - sed -i -e "s?^\(catmaid_database_username = \).*?\1'postgres'?g" configuration.py
  - sed -i -e "s?^\(catmaid_timezone = \).*?\1'America/New_York'?g" configuration.py
  - sed -i -e "s?^\(catmaid_servername = \).*?\1'localhost:8000'?g" configuration.py
  - cat configuration.py
  - python create_configuration.py
  - sed -i -e "s?^\(ALLOWED_HOSTS = \).*?\1['*']?g" projects/mysite/settings.py
  - cat projects/mysite/settings.py
  - cd ..
script:
  - jshint --config=.travis.jshintrc --exclude-path=.travis.jshintignore django/applications
  - cd django/projects/mysite
  - python manage.py syncdb --migrate --noinput
  - python manage.py collectstatic --link --noinput
  - coverage run --source=catmaid --omit='*management*,*migrations*,*tests*' manage.py test catmaid.tests djsopnet.tests
  # Remove login requirement from QUnit test page
  - sed -i 's/login_required(\([^)]*\))/\1/g' ../../applications/catmaid/urls.py
  - python manage.py runserver &
  - sleep 5
  - cd ../../..
  # Run QUnit tests through SlimerJS with Firefox
  - wget http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6.zip
  - unzip slimerjs-0.9.6.zip
  - mv slimerjs-0.9.6 ./slimerjs
  - ./.travis-run-slimerjs.sh http://localhost:8000/tests
after_success:
  - cd django/projects/mysite && coveralls
